### ISSUE TITLE
Installation : Minimerge executation failed

### ISSUE THREAD

**Issue by leplatrem** [mapnik/pymapnik2#2]
I followed instructions in minitage section, and had this error during the last step :

```
$ minimerge -av mapnik-egg
2012-03-22 09:25:00,557 DEBUG (Re)Initializing minitage logging system.
Minimerge executation failed:
        cannot deepcopy this pattern object
```

Any idea ?

Thanks !

If needed, the complete log is here : http://friendpaste.com/5x5nhKGRvvZ3XgLkst62kD

**Comment by leplatrem** [comment]
Using python 2.6, it goes further and starts compiling :

```
virtualenv --no-site-packages --distribute --python=python2.6 ~/minitage
...
...
```

But then there is a broken link among dependencies : 

```
MinimergeError: Failed download for http://gentoo.tiscali.nl/distfiles/freetype-2.4.8.tar.bz2:
```

Trace here : http://friendpaste.com/4iCtMEmXhEde2HDpBMSJtu

**Comment by kiorky** [comment]
fixed for a long time.
